import Foundation

struct OpenCodeWriteResult {
    let path: String
    let backupPath: String?
    let createdNew: Bool
    let warnings: [String]
    let fromMtplx: Bool   // canonical shape came from `mtplx connect`, not the built-in fallback
}

/// Writes (non-destructively, with backup) the OpenCode `mtplx` provider, pointed at the
/// router, and wires plan/build agents to planner/builder.
///
/// The provider shape is GENERATED by mtplx itself (`mtplx connect opencode --json`,
/// server-free) and we overlay our router URL + the enabled models — so the standalone
/// path writes the same canonical config ccstack does: `reasoning:false` (reasoning is
/// mtplx-owned, so OpenCode never imposes its own thinking budget — that budget is what
/// made long sessions loop), `output=context`, and the `x-mtplx-client` header. Falls back
/// to a built-in canonical shape if mtplx isn't reachable. NB: opencode.json is normally
/// owned by ccstack (reversible) — this is the explicit bypass.
enum OpenCodeConfigWriter {
    static var configURL: URL {
        URL(fileURLWithPath: expandTilde("~/.config/opencode/opencode.json"))
    }

    @discardableResult
    static func write() throws -> OpenCodeWriteResult {
        let cfg = ConfigStore.shared.config
        let enabled = cfg.models.filter { $0.enabled }
        guard !enabled.isEmpty else {
            throw RouterError.badRequest("no enabled models to write — add or enable a model first")
        }

        let url = configURL
        var warnings: [String] = []
        var backupPath: String? = nil
        var createdNew = false
        var root: [String: Any] = [:]

        if FileManager.default.fileExists(atPath: url.path) {
            let data = try Data(contentsOf: url)   // surfaces permission errors
            let bak = url.deletingLastPathComponent()
                .appendingPathComponent("opencode.json.bak-mtplxrouter-\(stamp())")
            try? data.write(to: bak); backupPath = bak.path
            if let obj = (try? JSONSerialization.jsonObject(with: data)) as? [String: Any] {
                root = obj
            } else {
                warnings.append("existing opencode.json was not valid JSON — wrote a fresh config; the old file is backed up.")
            }
        } else {
            createdNew = true
        }

        let base = "http://\(cfg.router.host):\(cfg.router.port)/v1"

        // Canonical provider shape, generated by mtplx (or the built-in fallback).
        let (canonical, fromMtplx) = mtplxCanonicalProvider(cfg.mtplxBinary)
        let canonicalModels = (canonical["models"] as? [String: Any]) ?? [:]
        let template = (canonicalModels.values.first as? [String: Any]) ?? canonicalModelFallback()

        // Provider-level options: canonical (x-mtplx-client header, timeout/chunkTimeout)
        // with OUR router baseURL. Drop mtplx's $MTPLX_API_KEY env-ref; set the router key
        // only if one is configured.
        var options = (canonical["options"] as? [String: Any]) ?? [:]
        options.removeValue(forKey: "apiKey")
        options["baseURL"] = base
        if !cfg.router.apiKey.isEmpty { options["apiKey"] = cfg.router.apiKey }

        // Per-model entries: clone the canonical template (reasoning:false, tool_call:true,
        // temperature:false, limit, modalities, + anything mtplx adds later), set our name.
        var models: [String: Any] = [:]
        for m in enabled {
            var entry = template
            entry["name"] = m.displayName
            models[m.id] = entry
        }

        var providers = root["provider"] as? [String: Any] ?? [:]
        providers["mtplx"] = [
            "npm": canonical["npm"] ?? "@ai-sdk/openai-compatible",
            "name": canonical["name"] ?? "MTPLX (local)",
            "options": options,
            "models": models,
        ]
        root["provider"] = providers

        // Agents: only set `model`, preserve prompt/temperature and everything else.
        let planner = enabled.first { $0.alias == "planner" } ?? enabled.first
        let builder = enabled.first { $0.alias == "builder" } ?? enabled.first
        var agent = root["agent"] as? [String: Any] ?? [:]
        if let planner = planner {
            var plan = agent["plan"] as? [String: Any] ?? [:]
            plan["model"] = "mtplx/\(planner.id)"; agent["plan"] = plan
        }
        if let builder = builder {
            var build = agent["build"] as? [String: Any] ?? [:]
            build["model"] = "mtplx/\(builder.id)"; agent["build"] = build
        }
        root["agent"] = agent
        if let builder = builder {
            root["model"] = "mtplx/\(builder.id)"
            root["small_model"] = "mtplx/\(builder.id)"
        }

        try FileManager.default.createDirectory(at: url.deletingLastPathComponent(), withIntermediateDirectories: true)

        // mtplx's session-headers plugin (carries x-mtplx-session-id so the prefix cache
        // stays warm across turns). Install the JS and reference it in `plugin`, preserving
        // any existing plugins.
        let pluginURL = url.deletingLastPathComponent().appendingPathComponent("mtplx-session-headers.js")
        try? sessionHeadersPlugin.data(using: .utf8)?.write(to: pluginURL)
        var plugins = (root["plugin"] as? [Any]) ?? []
        if !plugins.contains(where: { ($0 as? String) == pluginURL.path }) {
            plugins.append(pluginURL.path)
        }
        root["plugin"] = plugins

        // Local web tools MCP (private search + fetch), when enabled + installed.
        // Preserves any existing mcp servers; OpenCode spawns ours on demand.
        if cfg.webTools.enabled && WebToolsManager.isInstalled {
            var mcp = root["mcp"] as? [String: Any] ?? [:]
            mcp["mtplx-web"] = WebToolsManager.mcpEntry()
            root["mcp"] = mcp
        }

        let out = try JSONSerialization.data(withJSONObject: root,
                                             options: [.prettyPrinted, .sortedKeys, .withoutEscapingSlashes])
        try out.write(to: url)
        LogStore.shared.log("wrote OpenCode config → \(url.path) (canonical from mtplx: \(fromMtplx))")
        return OpenCodeWriteResult(path: url.path, backupPath: backupPath,
                                   createdNew: createdNew, warnings: warnings, fromMtplx: fromMtplx)
    }

    /// `mtplx connect opencode --json` -> `config.provider.mtplx` (+ true), or the built-in
    /// canonical fallback (+ false) when mtplx isn't reachable.
    private static func mtplxCanonicalProvider(_ bin: String) -> ([String: Any], Bool) {
        if let data = runCapture(bin, ["connect", "opencode", "--json"]),
           let root = (try? JSONSerialization.jsonObject(with: data)) as? [String: Any],
           let config = root["config"] as? [String: Any],
           let provider = config["provider"] as? [String: Any],
           let mtplx = provider["mtplx"] as? [String: Any] {
            return (mtplx, true)
        }
        return (canonicalProviderFallback(), false)
    }

    /// Built-in canonical provider (mirrors `mtplx connect opencode --json`, mtplx 1.0.4).
    private static func canonicalProviderFallback() -> [String: Any] {
        [
            "npm": "@ai-sdk/openai-compatible",
            "name": "MTPLX (local)",
            "options": [
                "timeout": false,
                "chunkTimeout": 900_000,
                "headers": ["x-mtplx-client": "opencode"],
            ],
            "models": ["_": canonicalModelFallback()],
        ]
    }

    private static func canonicalModelFallback() -> [String: Any] {
        [
            "name": "MTPLX local",
            "reasoning": false,
            "tool_call": true,
            "temperature": false,
            "limit": ["context": 262_144, "output": 262_144],
            "modalities": ["input": ["text"], "output": ["text"]],
        ]
    }

    /// Run a tool and capture stdout; nil on a missing binary, launch error, or nonzero exit.
    private static func runCapture(_ bin: String, _ args: [String]) -> Data? {
        guard FileManager.default.isExecutableFile(atPath: bin) else { return nil }
        let p = Process()
        p.executableURL = URL(fileURLWithPath: bin)
        p.arguments = args
        let out = Pipe(); p.standardOutput = out; p.standardError = Pipe()
        do { try p.run() } catch { return nil }
        let data = out.fileHandleForReading.readDataToEndOfFile()
        p.waitUntilExit()
        return p.terminationStatus == 0 ? data : nil
    }

    private static let sessionHeadersPlugin = """
    export const MTPLXSessionHeaders = async () => ({
      "chat.headers": async (input, output) => {
        output.headers ||= {};
        const providerID = input?.model?.providerID || input?.provider?.id;
        if (providerID && providerID !== "mtplx") return;
        output.headers["x-mtplx-client"] = "opencode";
        if (input?.sessionID) {
          output.headers["x-mtplx-session-id"] = String(input.sessionID);
        }
      }
    });
    export default MTPLXSessionHeaders;
    """

    private static func stamp() -> String {
        let f = DateFormatter(); f.dateFormat = "yyyyMMdd-HHmmss"; return f.string(from: Date())
    }
}
