import Foundation

/// The Qwen3.6 (`qwen3_5` family) chat-template fix.
///
/// The stock Qwen3.6 chat template raises `No user query found in messages` — an HTTP 500
/// at prompt-render time — whenever a conversation has no plain user turn (after context
/// compaction, or in deep agentic tool-loops). mtplx's default `--chat-template-profile
/// local_qwen36` uses the model's own (buggy) template, so the fix is to launch the daemon
/// with `--chat-template-path` pointing at a guard-free "hardened" template we ship.
///
/// Verified live on dense (27B) + MoE (35B-A3B): the 500 is gone and tool-calling is intact
/// (mtplx's hybrid tool contract is independent of the chat template).
enum QwenTemplateFix {
    static var dir: URL {
        FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
            .appendingPathComponent("MTPLX Router/templates", isDirectory: true)
    }
    static var templateURL: URL { dir.appendingPathComponent("qwen36_hardened.jinja") }
    static var templatePath: String { templateURL.path }

    /// Write the embedded hardened template to disk if missing. Idempotent; never clobbers
    /// an existing file (so a hand-verified template is preserved).
    static func ensureInstalled() {
        if FileManager.default.fileExists(atPath: templateURL.path) { return }
        guard let data = Data(base64Encoded: embeddedB64) else { return }
        try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        try? data.write(to: templateURL)
    }

    /// True when the model at `modelPath` is the Qwen3.5/3.6 family — dense `qwen3_5` or
    /// MoE `qwen3_5_moe` — i.e. the lineage whose stock template carries the buggy guard.
    static func isQwen35(modelPath: String) -> Bool {
        let cfg = URL(fileURLWithPath: modelPath).appendingPathComponent("config.json")
        guard let data = try? Data(contentsOf: cfg),
              let obj = (try? JSONSerialization.jsonObject(with: data)) as? [String: Any]
        else { return false }
        if let mt = obj["model_type"] as? String, mt.lowercased().hasPrefix("qwen3_5") { return true }
        if let arch = obj["architectures"] as? [String],
           arch.contains(where: { $0.lowercased().hasPrefix("qwen3_5") }) { return true }
        return false
    }

    /// base64 of the verified hardened template (sha256 060354fe…), decoded on first launch.
    static let embeddedB64 = "eyUtIG1hY3JvIG5vcm0oY29udGVudCkgLSV9CiAgICB7JS0gaWYgY29udGVudCBpcyBzdHJpbmcgLSV9CiAgICAgICAge3stIGNvbnRlbnQgLX19CiAgICB7JS0gZWxpZiBjb250ZW50IGlzIGl0ZXJhYmxlIGFuZCBjb250ZW50IGlzIG5vdCBtYXBwaW5nIC0lfQogICAgICAgIHslLSBmb3IgaXRlbSBpbiBjb250ZW50IC0lfQogICAgICAgICAgICB7JS0gaWYgJ3RleHQnIGluIGl0ZW0gLSV9e3stIGl0ZW0udGV4dCAtfX17JS0gZW5kaWYgLSV9CiAgICAgICAgeyUtIGVuZGZvciAtJX0KICAgIHslLSBlbmRpZiAtJX0KeyUtIGVuZG1hY3JvIC0lfQp7JS0gaWYgdG9vbHMgJX0KICAgIHt7LSAnPHxpbV9zdGFydHw+c3lzdGVtXG4nIH19CiAgICB7JS0gaWYgbWVzc2FnZXNbMF0ucm9sZSA9PSAnc3lzdGVtJyAlfQogICAgICAgIHslLSBzZXQgc2NvbnRlbnQgJX17eyBub3JtKG1lc3NhZ2VzWzBdLmNvbnRlbnQpIH19eyUgZW5kc2V0ICV9CiAgICAgICAge3stIHNjb250ZW50ICsgJ1xuXG4nIH19CiAgICB7JS0gZW5kaWYgJX0KICAgIHt7LSAiIyBUb29sc1xuXG5Zb3UgbWF5IGNhbGwgb25lIG9yIG1vcmUgZnVuY3Rpb25zIHRvIGFzc2lzdCB3aXRoIHRoZSB1c2VyIHF1ZXJ5LlxuXG5Zb3UgYXJlIHByb3ZpZGVkIHdpdGggZnVuY3Rpb24gc2lnbmF0dXJlcyB3aXRoaW4gPHRvb2xzPjwvdG9vbHM+IFhNTCB0YWdzOlxuPHRvb2xzPiIgfX0KICAgIHslLSBmb3IgdG9vbCBpbiB0b29scyAlfQogICAgICAgIHt7LSAiXG4iIH19CiAgICAgICAge3stIHRvb2wgfCB0b2pzb24gfX0KICAgIHslLSBlbmRmb3IgJX0KICAgIHt7LSAiXG48L3Rvb2xzPlxuXG5Gb3IgZWFjaCBmdW5jdGlvbiBjYWxsLCByZXR1cm4gYSBqc29uIG9iamVjdCB3aXRoIGZ1bmN0aW9uIG5hbWUgYW5kIGFyZ3VtZW50cyB3aXRoaW4gPHRvb2xfY2FsbD48L3Rvb2xfY2FsbD4gWE1MIHRhZ3M6XG48dG9vbF9jYWxsPlxue1wibmFtZVwiOiA8ZnVuY3Rpb24tbmFtZT4sIFwiYXJndW1lbnRzXCI6IDxhcmdzLWpzb24tb2JqZWN0Pn1cbjwvdG9vbF9jYWxsPjx8aW1fZW5kfD5cbiIgfX0KeyUtIGVsc2UgJX0KICAgIHslLSBpZiBtZXNzYWdlc1swXS5yb2xlID09ICdzeXN0ZW0nICV9CiAgICAgICAgeyUtIHNldCBzY29udGVudCAlfXt7IG5vcm0obWVzc2FnZXNbMF0uY29udGVudCkgfX17JSBlbmRzZXQgJX0KICAgICAgICB7ey0gJzx8aW1fc3RhcnR8PnN5c3RlbVxuJyArIHNjb250ZW50ICsgJzx8aW1fZW5kfD5cbicgfX0KICAgIHslLSBlbmRpZiAlfQp7JS0gZW5kaWYgJX0KeyUtIHNldCBucyA9IG5hbWVzcGFjZShtdWx0aV9zdGVwX3Rvb2w9dHJ1ZSwgbGFzdF9xdWVyeV9pbmRleD1tZXNzYWdlc3xsZW5ndGggLSAxKSAlfQp7JS0gZm9yIGZvcndhcmRfbWVzc2FnZSBpbiBtZXNzYWdlcyAlfQogICAgeyUtIHNldCBpbmRleCA9IChtZXNzYWdlc3xsZW5ndGggLSAxKSAtIGxvb3AuaW5kZXgwICV9CiAgICB7JS0gc2V0IG1lc3NhZ2UgPSBtZXNzYWdlc1tpbmRleF0gJX0KICAgIHslLSBzZXQgbWMgJX17eyBub3JtKG1lc3NhZ2UuY29udGVudCkgfX17JSBlbmRzZXQgJX0KICAgIHslLSBzZXQgbWMgPSBtYyB8IHRyaW0gJX0KICAgIHslLSBpZiBucy5tdWx0aV9zdGVwX3Rvb2wgYW5kIG1lc3NhZ2Uucm9sZSA9PSAidXNlciIgYW5kIG5vdChtYy5zdGFydHN3aXRoKCc8dG9vbF9yZXNwb25zZT4nKSBhbmQgbWMuZW5kc3dpdGgoJzwvdG9vbF9yZXNwb25zZT4nKSkgJX0KICAgICAgICB7JS0gc2V0IG5zLm11bHRpX3N0ZXBfdG9vbCA9IGZhbHNlICV9CiAgICAgICAgeyUtIHNldCBucy5sYXN0X3F1ZXJ5X2luZGV4ID0gaW5kZXggJX0KICAgIHslLSBlbmRpZiAlfQp7JS0gZW5kZm9yICV9CnslLSBmb3IgbWVzc2FnZSBpbiBtZXNzYWdlcyAlfQogICAgeyUtIHNldCBjb250ZW50ICV9e3sgbm9ybShtZXNzYWdlLmNvbnRlbnQpIH19eyUgZW5kc2V0ICV9CiAgICB7JS0gaWYgKG1lc3NhZ2Uucm9sZSA9PSAidXNlciIpIG9yIChtZXNzYWdlLnJvbGUgPT0gInN5c3RlbSIgYW5kIG5vdCBsb29wLmZpcnN0KSAlfQogICAgICAgIHt7LSAnPHxpbV9zdGFydHw+JyArIG1lc3NhZ2Uucm9sZSArICdcbicgKyBjb250ZW50ICsgJzx8aW1fZW5kfD4nICsgJ1xuJyB9fQogICAgeyUtIGVsaWYgbWVzc2FnZS5yb2xlID09ICJhc3Npc3RhbnQiICV9CiAgICAgICAgeyUtIHNldCByZWFzb25pbmdfY29udGVudCA9ICcnICV9CiAgICAgICAgeyUtIGlmIG1lc3NhZ2UucmVhc29uaW5nX2NvbnRlbnQgaXMgZGVmaW5lZCBhbmQgbWVzc2FnZS5yZWFzb25pbmdfY29udGVudCBpcyBub3Qgbm9uZSAlfQogICAgICAgICAgICB7JS0gc2V0IHJlYXNvbmluZ19jb250ZW50ID0gbWVzc2FnZS5yZWFzb25pbmdfY29udGVudCAlfQogICAgICAgIHslLSBlbHNlICV9CiAgICAgICAgICAgIHslLSBpZiAnPC90aGluaz4nIGluIGNvbnRlbnQgJX0KICAgICAgICAgICAgICAgIHslLSBzZXQgcmVhc29uaW5nX2NvbnRlbnQgPSAoY29udGVudC5zcGxpdCgnPC90aGluaz4nKSB8IGZpcnN0KS5yc3RyaXAoJ1xuJykgJX0KICAgICAgICAgICAgICAgIHslLSBzZXQgcmVhc29uaW5nX2NvbnRlbnQgPSAocmVhc29uaW5nX2NvbnRlbnQuc3BsaXQoJzx0aGluaz4nKSB8IGxhc3QpLmxzdHJpcCgnXG4nKSAlfQogICAgICAgICAgICAgICAgeyUtIHNldCBjb250ZW50ID0gKGNvbnRlbnQuc3BsaXQoJzwvdGhpbms+JykgfCBsYXN0KS5sc3RyaXAoJ1xuJykgJX0KICAgICAgICAgICAgeyUtIGVuZGlmICV9CiAgICAgICAgeyUtIGVuZGlmICV9CiAgICAgICAgeyUtIGlmIGxvb3AuaW5kZXgwID4gbnMubGFzdF9xdWVyeV9pbmRleCBhbmQgKGxvb3AubGFzdCBvciByZWFzb25pbmdfY29udGVudCkgJX0KICAgICAgICAgICAge3stICc8fGltX3N0YXJ0fD4nICsgbWVzc2FnZS5yb2xlICsgJ1xuPHRoaW5rPlxuJyArIHJlYXNvbmluZ19jb250ZW50LnN0cmlwKCdcbicpICsgJ1xuPC90aGluaz5cblxuJyArIGNvbnRlbnQubHN0cmlwKCdcbicpIH19CiAgICAgICAgeyUtIGVsc2UgJX0KICAgICAgICAgICAge3stICc8fGltX3N0YXJ0fD4nICsgbWVzc2FnZS5yb2xlICsgJ1xuJyArIGNvbnRlbnQgfX0KICAgICAgICB7JS0gZW5kaWYgJX0KICAgICAgICB7JS0gaWYgbWVzc2FnZS50b29sX2NhbGxzICV9CiAgICAgICAgICAgIHslLSBmb3IgdG9vbF9jYWxsIGluIG1lc3NhZ2UudG9vbF9jYWxscyAlfQogICAgICAgICAgICAgICAgeyUtIGlmIChsb29wLmZpcnN0IGFuZCBjb250ZW50KSBvciAobm90IGxvb3AuZmlyc3QpICV9CiAgICAgICAgICAgICAgICAgICAge3stICdcbicgfX0KICAgICAgICAgICAgICAgIHslLSBlbmRpZiAlfQogICAgICAgICAgICAgICAgeyUtIGlmIHRvb2xfY2FsbC5mdW5jdGlvbiAlfQogICAgICAgICAgICAgICAgICAgIHslLSBzZXQgdG9vbF9jYWxsID0gdG9vbF9jYWxsLmZ1bmN0aW9uICV9CiAgICAgICAgICAgICAgICB7JS0gZW5kaWYgJX0KICAgICAgICAgICAgICAgIHt7LSAnPHRvb2xfY2FsbD5cbnsibmFtZSI6ICInIH19CiAgICAgICAgICAgICAgICB7ey0gdG9vbF9jYWxsLm5hbWUgfX0KICAgICAgICAgICAgICAgIHt7LSAnIiwgImFyZ3VtZW50cyI6ICcgfX0KICAgICAgICAgICAgICAgIHslLSBpZiB0b29sX2NhbGwuYXJndW1lbnRzIGlzIHN0cmluZyAlfQogICAgICAgICAgICAgICAgICAgIHt7LSB0b29sX2NhbGwuYXJndW1lbnRzIH19CiAgICAgICAgICAgICAgICB7JS0gZWxzZSAlfQogICAgICAgICAgICAgICAgICAgIHt7LSB0b29sX2NhbGwuYXJndW1lbnRzIHwgdG9qc29uIH19CiAgICAgICAgICAgICAgICB7JS0gZW5kaWYgJX0KICAgICAgICAgICAgICAgIHt7LSAnfVxuPC90b29sX2NhbGw+JyB9fQogICAgICAgICAgICB7JS0gZW5kZm9yICV9CiAgICAgICAgeyUtIGVuZGlmICV9CiAgICAgICAge3stICc8fGltX2VuZHw+XG4nIH19CiAgICB7JS0gZWxpZiBtZXNzYWdlLnJvbGUgPT0gInRvb2wiICV9CiAgICAgICAgeyUtIGlmIGxvb3AuZmlyc3Qgb3IgKG1lc3NhZ2VzW2xvb3AuaW5kZXgwIC0gMV0ucm9sZSAhPSAidG9vbCIpICV9CiAgICAgICAgICAgIHt7LSAnPHxpbV9zdGFydHw+dXNlcicgfX0KICAgICAgICB7JS0gZW5kaWYgJX0KICAgICAgICB7ey0gJ1xuPHRvb2xfcmVzcG9uc2U+XG4nIH19CiAgICAgICAge3stIGNvbnRlbnQgfX0KICAgICAgICB7ey0gJ1xuPC90b29sX3Jlc3BvbnNlPicgfX0KICAgICAgICB7JS0gaWYgbG9vcC5sYXN0IG9yIChtZXNzYWdlc1tsb29wLmluZGV4MCArIDFdLnJvbGUgIT0gInRvb2wiKSAlfQogICAgICAgICAgICB7ey0gJzx8aW1fZW5kfD5cbicgfX0KICAgICAgICB7JS0gZW5kaWYgJX0KICAgIHslLSBlbmRpZiAlfQp7JS0gZW5kZm9yICV9CnslLSBpZiBhZGRfZ2VuZXJhdGlvbl9wcm9tcHQgJX0KICAgIHt7LSAnPHxpbV9zdGFydHw+YXNzaXN0YW50XG4nIH19CiAgICB7JS0gaWYgZW5hYmxlX3RoaW5raW5nIGlzIGRlZmluZWQgYW5kIGVuYWJsZV90aGlua2luZyBpcyBmYWxzZSAlfQogICAgICAgIHt7LSAnPHRoaW5rPlxuXG48L3RoaW5rPlxuXG4nIH19CiAgICB7JS0gZW5kaWYgJX0KeyUtIGVuZGlmICV9Cg=="
}
