import SwiftUI
import AppKit

final class SettingsModel: ObservableObject {
    @Published var cfg: AppConfig
    @Published var launchAtLogin: Bool
    init() {
        cfg = ConfigStore.shared.config
        launchAtLogin = LoginItem.isEnabled
    }
    func reload() {
        cfg = ConfigStore.shared.config
        launchAtLogin = LoginItem.isEnabled
    }
    func save() {
        ConfigStore.shared.save(cfg)
        if cfg.startup.startRouterOnLaunch || RouterServer.shared.isRunning {
            try? RouterServer.shared.start()   // re-bind host/port
        }
    }
}

final class SettingsWindowController: NSWindowController {
    convenience init() {
        let model = SettingsModel()
        let host = NSHostingController(rootView: SettingsView(model: model))
        let window = NSWindow(contentViewController: host)
        window.title = "MTPLX Router — Settings"
        window.styleMask = [.titled, .closable, .miniaturizable]
        window.setContentSize(NSSize(width: 580, height: 500))
        self.init(window: window)
    }
}

private func fileExists(_ p: String) -> Bool { FileManager.default.fileExists(atPath: p) }
private func isExec(_ p: String) -> Bool { FileManager.default.isExecutableFile(atPath: p) }

private struct StatusDot: View {
    let ok: Bool
    let okText: String
    let badText: String
    var body: some View {
        Label(ok ? okText : badText, systemImage: ok ? "checkmark.circle.fill" : "xmark.octagon.fill")
            .foregroundStyle(ok ? .green : .red)
            .font(.caption)
    }
}

struct SettingsView: View {
    @ObservedObject var model: SettingsModel
    @State private var alertText: String?

    private var issues: [Issue] { Diagnostics.configIssues(model.cfg) }

    var body: some View {
        VStack(spacing: 0) {
            if !issues.isEmpty {
                VStack(alignment: .leading, spacing: 4) {
                    ForEach(issues) { i in
                        Label("\(i.title) — \(i.detail)", systemImage: i.severity == .error ? "exclamationmark.octagon.fill" : "exclamationmark.triangle.fill")
                            .font(.caption)
                            .foregroundStyle(i.severity == .error ? .red : .orange)
                            .fixedSize(horizontal: false, vertical: true)
                    }
                }
                .frame(maxWidth: .infinity, alignment: .leading)
                .padding(10)
                .background(Color.yellow.opacity(0.12))
            }

            TabView {
                routerTab.tabItem { Text("Router") }
                modelsTab.tabItem { Text("Models") }
                startupTab.tabItem { Text("Startup") }
            }

            Divider()
            HStack {
                Button("Write OpenCode config") { writeOpenCode() }
                Spacer()
                Button("Revert") { model.reload() }
                Button("Save") { model.save() }.keyboardShortcut(.defaultAction)
            }
            .padding(12)
        }
        .frame(width: 580, height: 500)
        .alert("OpenCode", isPresented: Binding(get: { alertText != nil }, set: { if !$0 { alertText = nil } })) {
            Button("OK", role: .cancel) {}
        } message: { Text(alertText ?? "") }
    }

    private func writeOpenCode() {
        ConfigStore.shared.save(model.cfg)   // write current edits first
        do {
            let r = try OpenCodeConfigWriter.write()
            var m = (r.createdNew ? "Created " : "Updated ") + r.path
            if let b = r.backupPath { m += "\nBackup: \(b)" }
            m += r.fromMtplx ? "\nCanonical config generated by mtplx." : "\nmtplx unreachable — wrote built-in canonical config."
            for w in r.warnings { m += "\n⚠︎ \(w)" }
            alertText = m
        } catch { alertText = "Failed: \(error)" }
    }

    private var routerTab: some View {
        Form {
            Section("Router endpoint") {
                TextField("Host", text: $model.cfg.router.host)
                TextField("Port", value: $model.cfg.router.port, format: .number)
                SecureField("API key (blank = none)", text: $model.cfg.router.apiKey)
            }
            Section("Backend (mtplx)") {
                TextField("mtplx binary", text: $model.cfg.mtplxBinary)
                StatusDot(ok: isExec(model.cfg.mtplxBinary),
                          okText: "mtplx found",
                          badText: fileExists(model.cfg.mtplxBinary) ? "not executable" : "not found — install MTPLX or fix the path")
                TextField("Backend port", value: $model.cfg.backendPort, format: .number)
                Text("Where mtplx serves the model and the router forwards. Changing it restarts the daemon on the new port. If the Headroom hop is on, set ccstack’s headroom_upstream to match.")
                    .font(.caption).foregroundStyle(.secondary)
                    .fixedSize(horizontal: false, vertical: true)
                TextField("Health timeout (s)", value: $model.cfg.healthTimeoutSeconds, format: .number)
                TextField("Idle evict (min, 0 = never)", value: $model.cfg.idleEvictMinutes, format: .number)
            }
            Section("Web tools (private, local)") {
                StatusDot(ok: WebToolsManager.isInstalled && model.cfg.webTools.enabled,
                          okText: "on — web_search + web_fetch available to OpenCode",
                          badText: WebToolsManager.isInstalled ? "installed but off" : "not installed")
                Button(WebToolsManager.isInstalled && model.cfg.webTools.enabled ? "Manage…" : "Set up web tools…") {
                    NotificationCenter.default.post(name: .mtplxWebToolsSetup, object: nil)
                }
            }
        }
        .formStyle(.grouped)
    }

    private var modelsTab: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 8) {
                // Index identity, NOT $model.cfg.models: ModelEntry.id is user-editable, so
                // Identifiable's default (id-based) ForEach identity changes on every keystroke
                // in the id field and SwiftUI rebuilds the row — dropping keyboard focus. The
                // index is stable while editing fields.
                ForEach(model.cfg.models.indices, id: \.self) { i in
                    GroupBox {
                        VStack(alignment: .leading, spacing: 4) {
                            HStack {
                                Toggle("", isOn: $model.cfg.models[i].enabled).labelsHidden()
                                TextField("Display name", text: $model.cfg.models[i].displayName)
                            }
                            HStack {
                                TextField("model id", text: $model.cfg.models[i].id)
                                TextField("alias", text: $model.cfg.models[i].alias).frame(width: 110)
                            }
                            HStack {
                                TextField("path", text: $model.cfg.models[i].path)
                                    .font(.system(size: 11, design: .monospaced))
                                Button("Choose…") { chooseModelFolder(i) }
                            }
                            StatusDot(ok: fileExists(model.cfg.models[i].path), okText: "folder exists", badText: "folder not found")
                            if QwenTemplateFix.isQwen35(modelPath: model.cfg.models[i].path) {
                                Divider()
                                Toggle("Apply Qwen3.6 tool-call template fix", isOn: $model.cfg.models[i].templateFix)
                                    .font(.caption)
                                Text("Detected qwen3_5 family. Prevents the stock template’s “No user query found” 500 in long / compacted sessions (verified safe; tool-calling unaffected). Applies on next model load.")
                                    .font(.caption2).foregroundStyle(.secondary)
                                    .fixedSize(horizontal: false, vertical: true)
                            }
                        }
                        .padding(4)
                    }
                }
                HStack {
                    Button("Add model") {
                        model.cfg.models.append(ModelEntry(id: "new-model", alias: "", displayName: "New model",
                                                           path: expandTilde("~/.mtplx/models/")))
                    }
                    if model.cfg.models.count > 0 {
                        Button("Remove last", role: .destructive) { _ = model.cfg.models.popLast() }
                    }
                }
                .padding(.top, 4)
            }
            .padding(12)
        }
    }

    /// Finder folder picker for model `i`'s directory (the folder that holds config.json).
    private func chooseModelFolder(_ i: Int) {
        guard model.cfg.models.indices.contains(i) else { return }
        let panel = NSOpenPanel()
        panel.canChooseDirectories = true
        panel.canChooseFiles = false
        panel.allowsMultipleSelection = false
        panel.prompt = "Select"
        panel.message = "Select the model folder (the directory that contains config.json)"
        let current = model.cfg.models[i].path
        panel.directoryURL = URL(fileURLWithPath: current.isEmpty ? expandTilde("~/.mtplx/models") : current)
        if panel.runModal() == .OK, let url = panel.url {
            model.cfg.models[i].path = url.path
        }
    }

    private var startupTab: some View {
        Form {
            Section("Startup") {
                Toggle("Launch at login", isOn: Binding(
                    get: { model.launchAtLogin },
                    set: { v in
                        if LoginItem.set(v) { model.launchAtLogin = v; model.cfg.startup.launchAtLogin = v }
                        else { alertText = "Couldn’t change launch-at-login. Move “MTPLX Router.app” to /Applications and try again." }
                    }
                ))
                Toggle("Start router when app launches", isOn: $model.cfg.startup.startRouterOnLaunch)
                Picker("Preload on launch", selection: Binding(
                    get: { model.cfg.startup.preloadModelId ?? "" },
                    set: { model.cfg.startup.preloadModelId = $0.isEmpty ? nil : $0 }
                )) {
                    Text("None (lazy load)").tag("")
                    ForEach(model.cfg.models) { m in Text(m.displayName).tag(m.id) }
                }
            }
        }
        .formStyle(.grouped)
    }
}
